apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpbin
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadrunner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: roadrunner
        {{- .Values.labels | toYaml | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: httpbin
        resources: {}
