image: 
  repository: nginx
  tag: latest
labels:
  env: dev
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: agentpool
            operator: In
            values:
            - linux01