apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: roadrunner
  name: roadrunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadrunner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: roadrunner
        {{- .Values.labels | toYaml | nindent 8 }}
    spec:
      {{- if .Values.affinity }}
      affinity:
      {{- .Values.affinity | toYaml | nindent 8}}  
      {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: roadrunner
        resources: {}
