image: 
  repository: nginx
  tag: latest
labels:
  env: dev
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - key: agentpool
        operator: Equals
        values:
        - linux01
